apiVersion: v1
kind: Service
metadata:
  name: {{ include "base-deployment.name" . }}-svc
  labels:
    {{- include "base-deployment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "base-deployment.podLabels" . | nindent 4 }}
